version: "3"
services:

  901tol_dev:
    container_name: 901tol_dev
    build: ./901tol_dev
    volumes:
      - ../../:/usr/src/dev                         # for SorceCode
      - /var/run/docker.sock:/var/run/docker.sock   # for DooD
    working_dir: /usr/src/dev
    ports:
      - "2345:2345"
    tty: true
    stdin_open: true
    # networks:
    #   - myportfolio_k_dev_network

  ## for golang developments
  910tol_dev:
    container_name: 910tol_dev
    build: ./910tol_dev
    tty: true
    volumes:
      - ../../STGprd_devpkg/s_01_src/124api_src/src:/go/src
    ports:
      - "2345:2345"
      # Port No of Host(non-overlapable):Port No of Container(overlappable)
    # networks:
    #   - myportfolio_k_dev_network

# networks:
#   myportfolio_k_dev_network:
#     driver: bridge

#---note---+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+----#
# db-storeが生成されるような行為を行うときには「.sql」ファイルを
# 格納していないと初期化処理がスキップされるので注意！

# Dockerfile：コンテナ自体の初期設定のみ(動作に必要なツールのインストールと設定変更)記載
# docker-compose.yml：環境依存情報のみ(ポートとかストレージとか、プログラムの起動コマンドとか)記載
